{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-drdid
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DRDID_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DRDID/DRDID_{{ version }}.tar.gz
  sha256: 9ec099debe9028f8faa4d58b02c059054aa1d196606ade87b288609a2279526a

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bmisc                      # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-fastglm                    # [build_platform != target_platform]
    - r-parglm                     # [build_platform != target_platform]
    - r-trust                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bmisc >=1.4.1
    - r-rcpp >=1.0.12
    - r-fastglm >=0.0.3
    - r-parglm >=0.1.7
    - r-trust
  run:
    - r-base
    - r-bmisc >=1.4.1
    - r-rcpp >=1.0.12
    - r-fastglm >=0.0.3
    - r-parglm >=0.1.7
    - r-trust

test:
  commands:
    - $R -e "library('DRDID')"           # [not win]
    - "\"%R%\" -e \"library('DRDID')\""  # [win]

about:
  home: https://psantanna.com/DRDID/
  dev_url: https://github.com/pedrohcgs/DRDID
  license: GPL-3.0-only
  summary: Implements the locally efficient doubly robust difference-in-differences (DiD) estimators for the average treatment effect proposed by Sant'Anna and Zhao (2020) <doi:10.1016/j.jeconom.2020.06.003>. The estimator combines inverse probability weighting and outcome regression estimators (also implemented in the package)
    to form estimators with more attractive statistical properties. Two different estimation methods can be used to estimate the nuisance functions.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - JNuss71

# Package: DRDID
# Type: Package
# Title: Doubly Robust Difference-in-Differences Estimators
# Version: 1.0.6
# Authors@R: c(person("Pedro H. C.", "Sant'Anna", email = "pedrosantanna@causal-solutions.com", role = c("aut", "cre")), person("Jun", "Zhao", email = "beanzhaojun11@gmail.com",role = c("aut")) )
# Description: Implements the locally efficient doubly robust difference-in-differences (DiD) estimators for the average treatment effect proposed by Sant'Anna and Zhao (2020) <doi:10.1016/j.jeconom.2020.06.003>. The estimator combines inverse probability weighting and outcome regression estimators (also implemented in the package) to form estimators with more attractive statistical properties. Two different estimation methods can be used to estimate the nuisance functions.
# URL: https://psantanna.com/DRDID/, https://github.com/pedrohcgs/DRDID
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.5)
# Imports: stats, trust, BMisc (>= 1.4.1)
# RoxygenNote: 7.2.3
# Suggests: knitr, rmarkdown, spelling, testthat
# Date: 2023-05-18
# Language: en-US
# BugReports: https://github.com/pedrohcgs/DRDID/issues
# NeedsCompilation: no
# Packaged: 2023-05-18 17:04:27 UTC; pedrosantanna
# Author: Pedro H. C. Sant'Anna [aut, cre], Jun Zhao [aut]
# Maintainer: Pedro H. C. Sant'Anna <pedrosantanna@causal-solutions.com>
# Repository: CRAN
# Date/Publication: 2023-05-18 17:50:06 UTC
